// JavaScript Document
$('#banner').owlCarousel({
    loop:true,
    margin:0,
    nav:true,
    autoplay:true,
	autoplayTimeout:5000,
	smartSpeed:2000,
    responsive:{
        0:{
            items:1
        },
        600:{
            items:1
        },
        1000:{
            items:1
        }
    }
})


$('#banner1').owlCarousel({
    loop:true,
    margin:0,
    nav:true,
    autoplay:true,
	autoplayTimeout:5000,
	smartSpeed:2000,
    responsive:{
        0:{
            items:1
        },
        600:{
            items:1
        },
        1000:{
            items:1
        }
    }
})

$('#banner2').owlCarousel({
    loop:true,
    margin:0,
    nav:true,
    autoplay:true,
	autoplayTimeout:5000,
	smartSpeed:2000,
    responsive:{
        0:{
            items:1
        },
        600:{
            items:1
        },
        1000:{
            items:1
        }
    }
})